### PR TITLE
Ignore vim swaps

### PR DESCRIPTION
**Pull request by blomquisg**
/cc @agrare

### CODE REVIEW

**Comment by juliancheal** [comment]
LGTM 👍, but I can't merge.

**Comment by juliancheal** [comment]
@miq-bot assign @bronaghs

**Comment by agrare** [comment]
Who uses vim swapfiles anymore?  `echo 'set noswapfile' >> ~/.vimrc` :D

**Comment by juliancheal** [comment]
> This is ignored in the main repo so 👍 for the consistency

Shame we can't inherit ignore files…

**Comment by agrare** [comment]
> > This is ignored in the main repo so :+1: for the consistency
> 
> Shame we can't inherit ignore files…

Yeah maybe we can look at the main .gitignore, decide what we need and what we don't for the provider repos (looks like a lot is main repo specific), get them all consistent across the provider repos, and update the generator with the new .gitignore?

**Pull request merged**
