### PR TITLE
Added dependencies

### PR DESCRIPTION
**Pull request by chessbyte**
These were removed in https://github.com/ManageIQ/manageiq/pull/15043/commits/b1786113ee1bf7a78810c6436568e9eefba200df

### CODE REVIEW

**Comment by chessbyte** [comment]
@juliancheal Not sure why tests are failing.
@Fryguy without this, `bin/update` on main repo causes `LoadError: No such file to load -- fog/google` on my machine

**Comment by juliancheal** [comment]
Ah I think we need to do it like this:

` s.add_dependency("fog-google", [">=0.5.2"])`

**Comment by chessbyte** [comment]
@juliancheal Looking at http://guides.rubygems.org/specification-reference/#add_runtime_dependency for which `add_dependency` is an alias, shows the example similar to what I added there.

**Comment by juliancheal** [comment]
@chessbyte Ah, I had a vague feeling from someone telling me this recently, but guess not.

**Comment by juliancheal** [comment]
I tried running the tests locally, and I'm getting:

```
  1) ManageIQ::Providers::Google::CloudManager::Refresher will perform a full refresh
     Failure/Error: zones = @connection.zones.all
     
     Fog::Errors::Error:
       Required 'compute.zones.list' permission for 'projects/civil-tube-113314'
```

I realised I didn't copy over the VCR Cassettes, but even when I did that locally, that didn't change the test failure.

**Comment by juliancheal** [comment]
Created https://github.com/ManageIQ/manageiq-providers-google/pull/5 to add VCR Cassettes.

**Comment by lpichler** [comment]
currently is seed process broken without this PR
```
manageiq git:(master) ✗ /Users/liborpichler/manageiq/manageiq/bin/rails db:seed GOOD_MIGRATIONS=skip
=>
** override_gem: manageiq-ui-classic, [{:path=>"/Users/liborpichler/manageiq/manageiq-ui-classic"}], caller: /Users/liborpichler/manageiq/manageiq/bundler.d/Gemfile.dev.rb


** Using session_store: ActionDispatch::Session::MemCacheStore
rails aborted!
LoadError: No such file to load -- fog/google


/usr/local/Cellar/rbenv/1.1.0/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-providers-google-1c4e824fde31/app/models/manageiq/providers/google/cloud_manager/refresh_parser.rb:1:in `<top (required)>'
/Users/liborpichler/manageiq/manageiq/lib/extensions/require_nested.rb:11:in `require_nested'
/usr/local/Cellar/rbenv/1.1.0/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-providers-google-1c4e824fde31/app/models/manageiq/providers/google/cloud_manager.rb:10:in `<class:CloudManager>'
```

**Comment by juliancheal** [comment]
@lpichler I have a PR to fix this, just waiting for the tests to pass.

**Comment by juliancheal** [comment]
@chessbyte ok this PR is valid it's just missing the VCR Cassettes which my PR fixes, so merging.

**Pull request merged**
