### PR TITLE
[WIP] Updated Fog-google gem to 0.6.0

### PR DESCRIPTION
**Pull request by juliancheal**
This links to this issue https://github.com/ManageIQ/manageiq-providers-google/issues/17

### CODE REVIEW

**Comment by juliancheal** [comment]
Great the tests pass! 😂 Guess we need to update the tests 😹

**Comment by agrare** [comment]
Ha yeah we mock the response from fog https://github.com/ManageIQ/manageiq-providers-google/blob/master/spec/models/manageiq/providers/google/cloud_manager/metrics_capture_spec.rb#L182-L203 so these tests won't pickup on changes in the fog response format.

**Comment by juliancheal** [comment]
@miq-bot add_label wip

**Comment by juliancheal** [comment]
Now trying to get `:labels => schema[:target_to_google_labels].call(target),` working.

**Pull request closed without merging**
